version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "5565"
    volumes:
      - school-db-data:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
volumes:
  school-db-data:


